#include "/Engine/Public/Platform.ush"

//#define MAX_HEIGHT uint(65536)
#define MAX_HEIGHT uint(65536)
#define TERRAIN_SCALE uint(100)

void MainVS(float3 InPosition : ATTRIBUTE0, float2 InUV : ATTRIBUTE1, out float2 OutUV0 : TEXCOORD0, out float4 OutPosition : SV_POSITION)
{
	OutPosition = float4(InPosition.x * 2.0 - 1.0, 1.0 - 2.0 * InPosition.y, 0, 1);
	const float Dist = MAX_HEIGHT - distance(InPosition.z * TERRAIN_SCALE, MAX_HEIGHT);
	OutUV0.xy = Dist;
}
